package com.fury.game.node.entity.actor.figure.player

enum class Variables(val value: Any) {
    COAL_BAG_STORAGE(0),
    SMALL_POUCH_RUNE_ESSENCE(0),
    SMALL_POUCH_PURE_ESSENCE(0),
    MEDIUM_POUCH_RUNE_ESSENCE(0),
    MEDIUM_POUCH_PURE_ESSENCE(0),
    LARGE_POUCH_RUNE_ESSENCE(0),
    LARGE_POUCH_PURE_ESSENCE(0),
    GIANT_POUCH_RUNE_ESSENCE(0),
    GIANT_POUCH_PURE_ESSENCE(0),
    CROMPERTY_ESSENCE_CLAIMED(-1L),
    ARDOUGNE_CLOAK_RECHARGE(-1L),
    JAIL_TIME(0L),
    LAST_BORK_DEFEAT(0L),
}